# Generated by Django 4.1.1 on 2022-09-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderStatus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='OrderNumber',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
