# Generated by Django 4.1.1 on 2022-09-12 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrderStatus', '0003_alter_orderitems_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='id',
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='OrderNumber',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('SHIPPED', 'SHIPPED'), ('PENDING', 'PENDING'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=255),
        ),
    ]
